name: Generate Release Action
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1.11.1
        with:
          prerelease: ${{ contains(github.ref, '-rc.') }}
          generateReleaseNotes: true
